#!/usr/bin/env python3

#
# This file is part of the git-third-party distribution (https://github.com/kp2pml30/git-third-party).
# Copyright (c) 2024-2025 Kira Prokopenko kp2pml30@gmail.com
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

EXE_NAME = 'git third-party'

import subprocess
import os
import sys
import abc
import typing
import json
import textwrap
import io
import logging
from pathlib import Path

logging.basicConfig(stream=sys.stderr, level=logging.INFO)

GIT = os.getenv('GIT', 'git')

try:
	top_dir_str = subprocess.check_output(
		[GIT, 'rev-parse', '--show-toplevel'], text=True
	)
except Exception as e:
	print(
		f'could not execute `{GIT} rev-parse --show-toplevel`. You may wish to set `GIT` env variable',
		file=sys.stderr,
	)
	exit(1)

top_dir = Path(top_dir_str.strip())
cur_dir = Path(os.getcwd())

SAVED_FILES_PATH = top_dir.joinpath('.git-third-party')

PATCHES_PATH = SAVED_FILES_PATH.joinpath('patches')
CONFIG_PATH = SAVED_FILES_PATH.joinpath('config.json')

if not PATCHES_PATH.exists():
	logging.info(f'patches directory does not exist, creating path=`{PATCHES_PATH}`')
	PATCHES_PATH.mkdir(parents=True, exist_ok=True)

if not CONFIG_PATH.exists():
	config = {'repos': {}}
else:
	config = json.loads(CONFIG_PATH.read_text())


class Command:
	name: typing.ClassVar[str]
	help: str

	@abc.abstractmethod
	def handle(args: list[str]) -> None: ...

	def show_help(self, file: io.StringIO):
		file.write(f'subcommand `{self.name}`:\n')
		file.write(textwrap.indent(textwrap.dedent(self.help), prefix='\t').rstrip())
		file.write('\n')


def _get_patches_dir(name: str) -> Path:
	return PATCHES_PATH.joinpath(*name.split('/'))


def _dirty_check(name: str) -> None:
	target_dir = top_dir.joinpath(*name.split('/'))
	for opts in ([], ['--cached']):
		rs = subprocess.run(
			[GIT, 'diff', '--exit-code', '--quiet', *opts], check=False, cwd=target_dir
		)
		if rs.returncode != 0:
			raise GitThirdPartyException(f'repo {name} is dirty ( {target_dir} )')


def _update_at(name: str) -> None:
	conf = config['repos'][name]
	target_dir = top_dir.joinpath(*name.split('/'))
	logging.info(f'updating name={name} at path={target_dir}')
	if not target_dir.exists():
		target_dir.mkdir(parents=True, exist_ok=True)
		subprocess.run([GIT, 'init'], check=True, cwd=target_dir)
		subprocess.run(
			[GIT, 'remote', 'add', 'origin', conf['url']], check=True, cwd=target_dir
		)

	_dirty_check(name)
	rs = subprocess.run(
		[GIT, '-c', 'advice.detachedHead=false', 'checkout', conf['commit']],
		check=False,
		cwd=target_dir,
	)
	if rs.returncode != 0:
		logging.info(f'checking out {conf["commit"]} failed, fetching')
		subprocess.run(
			[GIT, 'fetch', 'origin', '--depth=1', conf['commit']],
			check=True,
			cwd=target_dir,
		)
		subprocess.run(
			[GIT, '-c', 'advice.detachedHead=false', 'checkout', conf['commit']],
			check=True,
			cwd=target_dir,
		)
	subprocess.run(
		[GIT, 'submodule', 'update', '--init', '--recursive', '--depth', '1'],
		check=True,
		cwd=target_dir,
	)
	submodules = conf.get('submodules', None)
	if submodules is None:
		logging.info('updating all submodules')
		subprocess.run(
			[GIT, 'submodule', 'update', '--recursive', '--depth', '1'],
			check=True,
			cwd=target_dir,
		)
	elif len(submodules) != 0:
		logging.info(f'updating submodules {submodules}')
		subprocess.run(
			[GIT, 'submodule', 'update', '--recursive', '--depth', '1', '--'] + submodules,
			check=True,
			cwd=target_dir,
		)
	# apply patches
	patches_dir = _get_patches_dir(name)
	patch_files = [patches_dir.joinpath(str(i)) for i in range(1, conf['patches'] + 1)]
	if len(patch_files) != 0:
		subprocess.run([GIT, 'am', *patch_files], cwd=target_dir, check=True)
	else:
		logging.warning(f'no patches detected')


class GitThirdPartyException(Exception):
	pass


def _get_path_rel_to_dir(path: str) -> str:
	target_dir = cur_dir.joinpath(Path(path))
	if top_dir not in target_dir.parents:
		raise GitThirdPartyException(
			f'target directory ({target_dir}) is not in git subtree ({top_dir})'
		)
	return str(target_dir.relative_to(top_dir)).replace(os.sep, '/')


class AddCommand(Command):
	name = 'add'
	help = f"""\
		{EXE_NAME} {name} <PATH> <REPO URL> <COMMIT>

		Adds a new repository to track
		Example: `{EXE_NAME} {name} third-party/my-cool-tool https://github.com/kp2pml30/git-third-party 4e6cc662a7e2b409e36d2412440c5670d6034431`
	"""

	def handle(self, args: list[str]) -> None:
		if len(args) != 3:
			print(f'Unexpected arguments {args}', file=sys.stderr)
			self.show_help(sys.stderr)
			exit(1)
		path, repo, commit = args
		import re

		if re.search(r'[\\:;]', path):
			print(f'bad path `{path}`', file=sys.stderr)
			exit(1)
		name = _get_path_rel_to_dir(path)
		if name in config['repos']:
			print(f'repo ({name}) is already in config', file=sys.stderr)
			exit(1)
		target_dir = top_dir.joinpath(*name.split('/'))
		res = subprocess.run([GIT, 'check-ignore', target_dir], check=False)
		if res.returncode != 0:
			raise GitThirdPartyException(
				f'target directory ({target_dir}) is not ignored by git'
			)
		config['repos'][name] = {
			'url': repo,
			'commit': commit,
			'patches': 0,
		}
		_update_at(name)


def _get_all_names() -> list[str]:
	return list(config['repos'].keys())


def _get_names_from_paths(paths: list[str]) -> list[str]:
	if len(paths) == 0:
		raise GitThirdPartyException('excepted non-empty list of arguments')
	if paths == ['--all']:
		return _get_all_names()
	return list(set(map(_get_path_rel_to_dir, paths)))


class UpdateCommand(Command):
	name = 'update'
	help = f"""\
		{EXE_NAME} {name} --all
		{EXE_NAME} {name} relative/path/to/repo/1 relative/path/to/repo/2

		restore state of specified repositories
	"""

	def handle(self, args):
		names = _get_names_from_paths(args)
		for name in names:
			_update_at(name)


class SaveCommand(Command):
	name = 'save'
	help = f"""\
		{EXE_NAME} {name} --all
		{EXE_NAME} {name} relative/path/to/repo/1 relative/path/to/repo/2

		record state of specified repositories
	"""

	def handle(self, args):
		names = _get_names_from_paths(args)
		for name in names:
			_save_at(name)


def _save_at(name: str) -> None:
	_dirty_check(name)
	target_dir = top_dir.joinpath(*name.split('/'))
	logging.info(f'saving name={name} at path={target_dir}')
	conf = config['repos'][name]
	patches_dir = _get_patches_dir(name)
	for i in range(1, conf['patches'] + 1):
		patches_dir.joinpath(str(i)).unlink()
	patches_dir.mkdir(parents=True, exist_ok=True)

	subprocess.run(
		[
			GIT,
			'format-patch',
			f'{conf["commit"]}..HEAD',
			'--no-numbered',
			'--zero-commit',
			'--no-signature',
			'--numbered-files',
			'-o',
			patches_dir,
		],
		check=True,
		cwd=target_dir,
	)
	new_patches = subprocess.run(
		[GIT, 'rev-list', '--count', f'{conf["commit"]}..HEAD'],
		check=True,
		cwd=target_dir,
		text=True,
		capture_output=True,
	)
	patches_cnt = int(new_patches.stdout.strip())
	logging.info(f'number of patches is {patches_cnt}')
	conf['patches'] = patches_cnt


mode = sys.argv[1] if len(sys.argv) > 1 else 'help'

handlers: dict[str, Command] = {}

for c in [UpdateCommand, SaveCommand, AddCommand]:
	handlers[c.name] = c()

mode_handler = handlers.get(mode, None)
if mode_handler is None:
	print(
		f'{EXE_NAME} expected one of following subcommands: ' + '|'.join(handlers.keys()),
		file=sys.stderr,
	)
	for k in handlers.values():
		k.show_help(sys.stderr)
	exit(1)

try:
	mode_handler.handle(sys.argv[2:])
except GitThirdPartyException as e:
	print(*e.args, file=sys.stderr)
	exit(1)

import json

with open(CONFIG_PATH, 'wt') as f:
	json.dump(config, f, indent='\t')
	f.write('\n')
