#!/usr/bin/env python3

import argparse
import re
import sys
import unicodedata
from dataclasses import dataclass

VALID_TYPES = r'feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert'
COMMIT_FORMAT_RE = re.compile(rf'^({VALID_TYPES})(\([a-zA-Z0-9_-]+\))?!?: .+$')

AI_PATTERNS = [
	re.compile(p, re.IGNORECASE)
	for p in [
		r'Co-Authored-By:.*claude',
		r'Co-Authored-By:.*gpt',
		r'Co-Authored-By:.*copilot',
		r'Co-Authored-By:.*anthropic',
		r'Co-Authored-By:.*openai',
		r'Co-Authored-By:.*\bai\b',
		r'Co-Authored-By:.*noreply@anthropic',
		r'generated by',
		r'generated with',
		r'created by claude',
		r'created with claude',
		r'created by gpt',
		r'created with gpt',
		r'claude[\s-]code',
		r'Claude-Session:\s*https?://',
	]
]

TICKET_PATTERNS = [
	re.compile(p, re.IGNORECASE)
	for p in [
		r'fixes #\d+',
		r'closes #\d+',
		r'resolves #\d+',
		r'part of [A-Z]+-\d+',
		r'related to [A-Z]+-\d+',
		r'fixes [A-Z]+-\d+',
	]
]

SUBJECT_LEN_SUGGESTED = 72
SUBJECT_LEN_MAX = 120
TRAILING_EMOJI_MAX = 5

BODY_MIN_WORDS = 3
BODY_MIN_CHARS = 20

# Matches git trailer lines: "Token: value" (Co-authored-by:, Signed-off-by:, etc.)
GIT_TRAILER_RE = re.compile(r'^[A-Za-z][A-Za-z0-9-]*:\s*.+$')

PR_REF_RE = re.compile(r'\s*\(#\d+\)\s*$')
SQUASH_BULLET_RE = re.compile(r'^\*\s*')


_EMOJI_MODIFIERS = frozenset([0xFE0F, 0xFE0E, 0x200D, 0x20E3])


def _is_emoji_char(ch: str) -> bool:
	cp = ord(ch)
	if cp in _EMOJI_MODIFIERS:
		return True
	cat = unicodedata.category(ch)
	if cat in ('So', 'Sm') and cp > 0x2000:
		return True
	if 0x1F300 <= cp <= 0x1FAFF:
		return True
	if 0x2600 <= cp <= 0x27BF:
		return True
	return False


def _split_trailing_emojis(text: str) -> tuple[str, str]:
	"""Return (prefix, suffix) where suffix is trailing spaces+emojis."""
	i = len(text)
	while i > 0 and (text[i - 1] == ' ' or _is_emoji_char(text[i - 1])):
		i -= 1
	return text[:i], text[i:]


def _count_emojis(text: str) -> int:
	return sum(1 for ch in text if _is_emoji_char(ch) and ord(ch) not in _EMOJI_MODIFIERS)


def _body_without_trailers(body: str) -> str:
	"""Strip git trailer lines from body text, return the remaining content."""
	lines = [line for line in body.splitlines() if not GIT_TRAILER_RE.match(line.strip())]
	return '\n'.join(lines).strip()


def _first_match(patterns: list[re.Pattern], text: str) -> str | None:
	for pat in patterns:
		m = pat.search(text)
		if m:
			return m.group()
	return None


@dataclass
class CommitPart:
	title: str
	body: str = ''


def parse_commit(message: str) -> list[CommitPart]:
	"""Split a commit message into parts to validate independently.

	A squash/PR-merge commit (GitHub style) has bullet lines in the body that
	are themselves conventional commit subjects.  Each becomes its own CommitPart;
	the umbrella title becomes the first part with any non-bullet body text.
	A regular commit returns a single CommitPart.
	"""
	lines = message.splitlines()
	title = lines[0] if lines else ''
	body_lines = lines[1:] if len(lines) > 1 else []

	squash_parts: list[CommitPart] = []
	non_bullet: list[str] = []

	for line in body_lines:
		stripped = line.strip()
		if not stripped:
			continue
		m = SQUASH_BULLET_RE.match(stripped)
		if m:
			bullet = stripped[m.end() :]
			clean, _ = _split_trailing_emojis(PR_REF_RE.sub('', bullet))
			if COMMIT_FORMAT_RE.match(clean):
				squash_parts.append(CommitPart(title=bullet))
				continue
		non_bullet.append(line)

	umbrella = CommitPart(title=title, body='\n'.join(non_bullet).strip())
	return [umbrella, *squash_parts] if squash_parts else [umbrella]


def _check_subject(subject: str, errors: list[str], warnings: list[str]) -> None:
	clean, suffix = _split_trailing_emojis(PR_REF_RE.sub('', subject))

	if not COMMIT_FORMAT_RE.match(clean):
		errors.append('Invalid format. Expected: <type>(<scope>): <subject> [emoji…]')
		errors.append(f"  Got: '{subject}'")
		errors.append(f'  Valid types: {VALID_TYPES.replace("|", ", ")}')

	if _count_emojis(clean) > 0:
		errors.append(
			f"Emojis must only appear at the end of the subject line: '{subject}'"
		)

	n = _count_emojis(suffix)
	if n > TRAILING_EMOJI_MAX:
		warnings.append(f'Too many trailing emojis ({n}). Max {TRAILING_EMOJI_MAX}.')

	length = len(subject)
	if length > SUBJECT_LEN_MAX:
		errors.append(
			f'Subject too long ({length} chars). Maximum: {SUBJECT_LEN_MAX} chars'
		)
	elif length > SUBJECT_LEN_SUGGESTED:
		warnings.append(
			f'Subject exceeds {SUBJECT_LEN_SUGGESTED} chars ({length} chars). Consider shortening.'
		)


def validate_part(part: CommitPart) -> tuple[list[str], list[str]]:
	errors: list[str] = []
	warnings: list[str] = []

	_check_subject(part.title, errors, warnings)

	if hit := _first_match(AI_PATTERNS, part.title + '\n' + part.body):
		errors.append(f"AI attribution detected: '{hit}'.")
		errors.append(
			'  Commits must not contain AI tool references or Co-Authored-By with AI names.'
		)

	real_body = _body_without_trailers(part.body)
	if real_body:
		words = len(real_body.split())
		chars = len(real_body)
		if words < BODY_MIN_WORDS or chars < BODY_MIN_CHARS:
			warnings.append(
				f'Commit body is very short ({words} word(s), {chars} char(s)). Are you sure you need a body?'
			)

	if _count_emojis(part.body) > 0:
		errors.append('Emojis in the commit body are not allowed.')

	if hit := _first_match(TICKET_PATTERNS, part.body):
		warnings.append(
			f"Ticket reference in commit body ('{hit}'). Move to PR description instead."
		)

	return errors, warnings


def validate(message: str) -> tuple[list[str], list[str]]:
	all_errors: list[str] = []
	all_warnings: list[str] = []
	for part in parse_commit(message):
		errors, warnings = validate_part(part)
		all_errors.extend(errors)
		all_warnings.extend(warnings)
	return all_errors, all_warnings


def main() -> int:
	parser = argparse.ArgumentParser(
		description='Validate a commit message against conventional commit rules.'
	)
	group = parser.add_mutually_exclusive_group(required=True)
	group.add_argument(
		'--message-file', metavar='FILE', help='Path to file containing the commit message'
	)
	group.add_argument('--message-text', metavar='TEXT', help='Commit message text')
	args = parser.parse_args()

	if args.message_file:
		if args.message_file == '-':
			message = sys.stdin.read()
		else:
			with open(args.message_file, encoding='utf-8') as f:
				message = f.read()
	else:
		message = args.message_text

	errors, warnings = validate(message)

	if warnings:
		print(f'Warnings ({len(warnings)}):')
		for w in warnings:
			print(f'  {w}')

	if errors:
		print(f'\nErrors ({len(errors)}):')
		for e in errors:
			print(f'  {e}')
		print()
		print('Commit message rules:')
		print('  - Format: <type>(<scope>): <subject>')
		print(f'  - Types: {VALID_TYPES.replace("|", ", ")}')
		print(
			f'  - Title: <={SUBJECT_LEN_SUGGESTED} chars recommended, <={SUBJECT_LEN_MAX} max'
		)
		print("  - NO AI attribution (Co-Authored-By with AI, 'Generated by', etc.)")
		print('  - NO ticket references in body (use PR description)')
		return 1

	print('Commit message is valid.')
	return 0


if __name__ == '__main__':
	sys.exit(main())
